package view;


import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 182120001
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        JMI_Cliente_ = new javax.swing.JMenuItem();
        JMI_Editora_ = new javax.swing.JMenuItem();
        JMI_Livro_ = new javax.swing.JMenuItem();
        JMI_VendaLivro_ = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Livraria");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/livrosss.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 294, 228));

        jMenuBar2.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar2.setForeground(new java.awt.Color(255, 255, 255));

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setForeground(new java.awt.Color(0, 0, 0));
        jMenu1.setMnemonic('G');
        jMenu1.setText("Gerenciar");
        jMenu1.setToolTipText("");

        JMI_Cliente_.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JMI_Cliente_.setBackground(new java.awt.Color(255, 255, 255));
        JMI_Cliente_.setForeground(new java.awt.Color(0, 0, 0));
        JMI_Cliente_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon/cliente (1).png"))); // NOI18N
        JMI_Cliente_.setText("Cliente");
        JMI_Cliente_.setToolTipText("Cadastrar, Atualizar, Deletar e Listar Clientes");
        JMI_Cliente_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_Cliente_ActionPerformed(evt);
            }
        });
        jMenu1.add(JMI_Cliente_);

        JMI_Editora_.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JMI_Editora_.setBackground(new java.awt.Color(255, 255, 255));
        JMI_Editora_.setForeground(new java.awt.Color(0, 0, 0));
        JMI_Editora_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon/companhia.png"))); // NOI18N
        JMI_Editora_.setText("Editora");
        JMI_Editora_.setToolTipText("Cadastar, Atualizar, Deletar e Listar Editoras");
        JMI_Editora_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_Editora_ActionPerformed(evt);
            }
        });
        jMenu1.add(JMI_Editora_);

        JMI_Livro_.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JMI_Livro_.setBackground(new java.awt.Color(255, 255, 255));
        JMI_Livro_.setForeground(new java.awt.Color(0, 0, 0));
        JMI_Livro_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon/pilha-de-livros.png"))); // NOI18N
        JMI_Livro_.setText("Livro");
        JMI_Livro_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_Livro_ActionPerformed(evt);
            }
        });
        jMenu1.add(JMI_Livro_);

        jMenuBar2.add(jMenu1);

        JMI_VendaLivro_.setForeground(new java.awt.Color(0, 0, 0));
        JMI_VendaLivro_.setMnemonic('V');
        JMI_VendaLivro_.setText("Venda Livro");
        jMenuBar2.add(JMI_VendaLivro_);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 991, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMI_Cliente_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_Cliente_ActionPerformed
        jfCliente janelaCliente = new jfCliente();
        janelaCliente.setVisible(true);
    }//GEN-LAST:event_JMI_Cliente_ActionPerformed

    private void JMI_Editora_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_Editora_ActionPerformed
        jfEditora janelaEditora = new jfEditora();
        janelaEditora.setVisible(true);
    }//GEN-LAST:event_JMI_Editora_ActionPerformed

    private void JMI_Livro_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_Livro_ActionPerformed
        jfLivro janelaLivro = new jfLivro();
        janelaLivro.setVisible(true);
    }//GEN-LAST:event_JMI_Livro_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMI_Cliente_;
    private javax.swing.JMenuItem JMI_Editora_;
    private javax.swing.JMenuItem JMI_Livro_;
    private javax.swing.JMenu JMI_VendaLivro_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
